import { FACT_EXTRACTION_GRAMMAR, getExtractionPrompt } from './grammars';
import { type SQLiteDatabase } from 'expo-sqlite';
import { createKnowledgeManager } from './KnowledgeManager';

/**
 * 🛡️ Interfaces for Llama.cpp integration
 */
interface LlamaCompletionOptions {
  prompt: string;
  grammar?: string;
  n_predict?: number;
  temperature?: number;
  stop?: string[];
  slot_id?: number;
  cache_prompt?: boolean;
  isBackground?: boolean;
}

interface LlamaCompletionResponse {
  text: string;
  [key: string]: any;
}

interface LlamaContext {
  completion: (options: LlamaCompletionOptions) => Promise<LlamaCompletionResponse | string>;
}

interface ExtractedFact {
  category: string;
  fact: string;
  confidence: number;
}

interface ExtractionResult {
  facts: ExtractedFact[];
}

/**
 * 🧠 FactExtractionService
 * Responsible for analyzing conversations and extracting facts for syntactic memory.
 */
export class FactExtractionService {
  /**
   * Analyzes the message exchange and persists extracted facts.
   * @param llamaContext The LLM execution context.
   * @param userMsg The message sent by the user.
   * @param aiMsg The response generated by the AI.
   * @param db The Expo SQLite database instance.
   */
  async extractFacts(llamaContext: LlamaContext, userMsg: string, aiMsg: string, db: SQLiteDatabase): Promise<void> {
    try {
      const prompt = getExtractionPrompt(userMsg, aiMsg);

      const response = await llamaContext.completion({
        prompt,
        grammar: FACT_EXTRACTION_GRAMMAR,
        n_predict: 256,
        temperature: 0,
        stop: ["<eos>", "<end_of_turn>", "<|im_end|>", "<|eot_id|>", "<turn|>", "<|turn|>"],
        isBackground: true,
      });

      const text = typeof response === 'string' ? response : response.text;
      if (!text) return;

      const parsed = this.safeParseExtraction(text);
      if (!parsed || parsed.facts.length === 0) return;

      // Persist facts in the database using the KnowledgeManager
      const knowledgeManager = createKnowledgeManager(db);
      await Promise.all(
        parsed.facts.map(fact => knowledgeManager.saveFact({
          fact: fact.fact,
          source: 'Conversation',
          confidence: fact.confidence,
          category: fact.category
        }))
      );

    } catch (error) {
      console.error('[FactExtractionService] Error during fact extraction:', error);
    }
  }

  /**
   * Parses the extraction JSON with basic structure validation.
   */
  private safeParseExtraction(text: string): ExtractionResult | null {
    try {
      let cleaned = text.trim();

      // Remove markdown code block formatting if present
      if (cleaned.startsWith('```')) {
        cleaned = cleaned.replace(/^```(?:json)?\n?/, '');
        cleaned = cleaned.replace(/\n?```$/, '');
        cleaned = cleaned.trim();
      }

      // Extract the first valid curly-braces JSON block via brace counting
      const startIdx = cleaned.indexOf('{');
      if (startIdx !== -1) {
        let braceCount = 0;
        for (let i = startIdx; i < cleaned.length; i++) {
          const char = cleaned[i];
          if (char === '{') {
            braceCount++;
          } else if (char === '}') {
            braceCount--;
            if (braceCount === 0) {
              cleaned = cleaned.substring(startIdx, i + 1);
              break;
            }
          }
        }
      }

      const data = JSON.parse(cleaned) as ExtractionResult;
      
      if (!data || !Array.isArray(data.facts)) {
        return null;
      }

      // Filter malformed facts
      data.facts = data.facts.filter(f => 
        f && 
        typeof f.category === 'string' && 
        typeof f.fact === 'string' && 
        typeof f.confidence === 'number'
      );

      return data;
    } catch (e) {
      console.log('[FactExtractionService] Handled JSON parse exception for text:', text);
      return null;
    }
  }
}

// Export a singleton instance for easier use in hooks
export const factExtractionService = new FactExtractionService();