// Textos extendidos para los resultados de los tests psicométricos (300-500 palabras por test en total combinando propósito y análisis).

export const TEST_PURPOSES = {
  aptitude: {
    en: "The Cognitive Aptitudes Test is a comprehensive assessment designed to measure your fundamental reasoning capabilities across multiple cognitive domains, including logical, numerical, verbal, and spatial reasoning. Unlike a standard knowledge test, this evaluation focuses on fluid intelligence—your inherent ability to process new information, recognize underlying patterns, and solve abstract problems under pressure. Understanding your cognitive profile helps in identifying the types of tasks where you naturally excel and those that may require more deliberate practice. This self-awareness is crucial for career planning, academic pursuits, and personal development, allowing you to align your goals with your innate analytical strengths.",
    es: "El Test de Aptitudes Cognitivas es una evaluación integral diseñada para medir tus capacidades fundamentales de razonamiento en múltiples dominios cognitivos, incluyendo el razonamiento lógico, numérico, verbal y espacial. A diferencia de un test de conocimientos estándar, esta evaluación se enfoca en la inteligencia fluida: tu habilidad inherente para procesar nueva información, reconocer patrones subyacentes y resolver problemas abstractos bajo presión. Comprender tu perfil cognitivo ayuda a identificar los tipos de tareas en las que destacas naturalmente y aquellas que podrían requerir práctica más deliberada. Este autoconocimiento es crucial para la planificación profesional, los objetivos académicos y el desarrollo personal, permitiéndote alinear tus metas con tus fortalezas analíticas innatas."
  },
  anxiety: {
    en: "The Emotional Balance Test is a screening tool adapted from established psychological frameworks (like the GAD-7) to evaluate your current level of emotional tension and nervousness over the past two weeks. Its purpose is to provide a snapshot of your psychological state, helping you identify if the stress you are experiencing is within typical bounds or if it is beginning to disrupt your daily functioning. By measuring physical and cognitive symptoms of anxiety, this tool acts as an early warning system. Please note that this test is not a professional test, but a personal wellness guide and not a medical diagnosis. The goal is to equip you with insights to proactively manage your well-being.",
    es: "El Test de Balance Emocional es una herramienta de cribado adaptada de marcos psicológicos establecidos (como el GAD-7) para evaluar tu nivel actual de tensión emocional y nerviosismo durante las últimas dos semanas. Su propósito es proporcionar una instantánea de tu estado psicológico, ayudándote a identificar si el estrés que experimentas está dentro de los límites típicos o si está comenzando a interrumpir tu funcionamiento diario. Al medir síntomas físicos y cognitivos de ansiedad, esta herramienta actúa como un sistema de alerta temprana. Ten en cuenta que este test no es un test profesional, sino una guía de bienestar personal y no un diagnóstico médico. El objetivo es equiparte con conocimientos para gestionar tu bienestar de manera proactiva."
  },
  mood: {
    en: "The Emotional Well-being Test is designed to assess your current mood and overall psychological flourishing, drawing on principles from the PHQ-9 and WHO-5 indices. This assessment goes beyond merely detecting sadness; it measures your sense of purpose, energy levels, social connectedness, and capacity for joy over the past two weeks. Emotional well-being fluctuates naturally with life's demands, and this tool helps you track your baseline. By understanding your current emotional state, you can make informed decisions about your daily routines, self-care practices, and know when it might be beneficial to seek additional support to improve your quality of life. This test is not a professional test.",
    es: "El Test de Bienestar Emocional está diseñado para evaluar tu estado de ánimo actual y tu florecimiento psicológico general, basándose en los principios de los índices PHQ-9 y WHO-5. Esta evaluación va más allá de simplemente detectar la tristeza; mide tu sentido de propósito, niveles de energía, conexión social y capacidad para la alegría durante las últimas dos semanas. El bienestar emocional fluctúa naturalmente con las demandas de la vida, y esta herramienta te ayuda a monitorear tu línea base. Al comprender tu estado emocional actual, puedes tomar decisiones informadas sobre tus rutinas diarias, prácticas de autocuidado y saber cuándo podría ser beneficioso buscar apoyo adicional para mejorar tu calidad de vida. Este test no es un test profesional."
  },
  vocational: {
    en: "The Vocational Test is based on the Holland Codes (RIASEC) theory, which posits that both people and work environments can be categorized into six distinct personality types. The purpose of this assessment is to identify your dominant occupational interests and the types of environments where you are most likely to thrive, feel satisfied, and remain motivated. By mapping your preferences—whether you lean towards hands-on tasks, analytical problem-solving, creative expression, social interaction, leadership, or structural organization—this tool provides a framework for career exploration. Aligning your career path with your core vocational type significantly increases the probability of long-term professional fulfillment.",
    es: "El Test Vocacional se basa en la teoría de los Códigos de Holland (RIASEC), la cual postula que tanto las personas como los entornos de trabajo pueden categorizarse en seis tipos de personalidad distintos. El propósito de esta evaluación es identificar tus intereses ocupacionales dominantes y los tipos de entornos donde tienes más probabilidades de prosperar, sentirte satisfecho y mantenerte motivado. Al mapear tus preferencias (ya sea hacia tareas manuales, resolución analítica de problemas, expresión creativa, interacción social, liderazgo u organización estructural), esta herramienta proporciona un marco para la exploración profesional. Alinear tu trayectoria profesional con tu tipo vocacional central aumenta significativamente la probabilidad de realización profesional a largo plazo."
  },
  mbti: {
    en: "The 16 Personalities (MBTI) Test is a psychological assessment designed to measure and categorize how individuals perceive the world and make decisions. Based on Carl Jung's theory of psychological types, it evaluates four primary dichotomies: Extraversion vs. Introversion (where you direct your energy), Sensing vs. Intuition (how you process information), Thinking vs. Feeling (how you make decisions), and Judging vs. Perceiving (how you organize your life). The purpose of this assessment is not to limit you to a rigid box, but to provide a vocabulary for understanding your natural behavioral inclinations. This profound self-knowledge is instrumental for improving communication, optimizing teamwork, and fostering personal growth.",
    es: "El Test de 16 Personalidades (MBTI) es una evaluación psicológica diseñada para medir y categorizar cómo los individuos perciben el mundo y toman decisiones. Basado en la teoría de los tipos psicológicos de Carl Jung, evalúa cuatro dicotomías principales: Extraversión vs. Introversión (hacia dónde diriges tu energía), Sensación vs. Intuición (cómo procesas la información), Pensamiento vs. Sentimiento (cómo tomas decisiones) y Juicio vs. Percepción (cómo organizas tu vida). El propósito de esta evaluación no es encasillarte, sino proporcionar un vocabulario para comprender tus inclinaciones conductuales naturales. Este profundo autoconocimiento es fundamental para mejorar la comunicación, optimizar el trabajo en equipo y fomentar el crecimiento personal."
  }
};

export const OCEAN_GUIDE = {
  en: "The OCEAN+ framework represents a modern expansion of the classical Big Five personality model, universally recognized as the most scientifically robust methodology for evaluating human personality. The core dimensions—Openness, Conscientiousness, Extraversion, Agreeableness, and Emotional Stability (Neuroticism reversed)—form the bedrock of your psychological profile. In this enhanced '+' version, we also measure Decision Speed and Learning Style to provide a more holistic view of how you navigate modern complexities. \n\nNo single dimension is inherently 'good' or 'bad'. Instead, they represent a spectrum of behavioral strategies. High Openness correlates with creativity but can lead to scattered focus; high Conscientiousness predicts career success but may result in rigidity. Your unique combination of these traits creates a specific psychological signature that dictates how you interact with your environment. Understanding your OCEAN+ profile allows you to design your life around your natural tendencies, leaning into your strengths while proactively managing the blind spots associated with your extremes.",
  es: "El marco OCEAN+ representa una expansión moderna del modelo clásico de los Cinco Grandes (Big Five), universalmente reconocido como la metodología científicamente más robusta para evaluar la personalidad humana. Las dimensiones centrales (Apertura, Responsabilidad, Extraversión, Amabilidad y Estabilidad Emocional) forman la base de tu perfil psicológico. En esta versión mejorada '+', también medimos la Velocidad de Decisión y el Estilo de Aprendizaje para proporcionar una visión más holística de cómo navegas las complejidades modernas.\n\nNinguna dimensión es inherentemente 'buena' o 'mala'. En cambio, representan un espectro de estrategias conductuales. Una alta Apertura se correlaciona con la creatividad pero puede llevar a una atención dispersa; una alta Responsabilidad predice el éxito profesional pero puede resultar en rigidez. Tu combinación única de estos rasgos crea una firma psicológica específica que dicta cómo interactúas con tu entorno. Comprender tu perfil OCEAN+ te permite diseñar tu vida en torno a tus tendencias naturales, apoyándote en tus fortalezas mientras gestionas proactivamente los puntos ciegos asociados a tus extremos."
};

export const APTITUDE_LEVELS_TEXT: Record<string, { en: string; es: string }> = {
  Exceptional: {
    en: "Your results indicate an Exceptional level of cognitive aptitude, placing you in the highest percentile of reasoning capabilities. You demonstrate an extraordinary capacity to synthesize complex information, identify abstract patterns, and apply logical structures to novel problems with remarkable speed. This level of fluid intelligence suggests that you are highly capable of thriving in cognitively demanding environments such as advanced data science, theoretical physics, complex strategic planning, or high-stakes engineering. To maximize this potential, it is essential that you continuously challenge yourself with problems that force you out of your comfort zone, preventing intellectual stagnation.",
    es: "Tus resultados indican un nivel Excepcional de aptitud cognitiva, ubicándote en el percentil más alto de capacidades de razonamiento. Demuestras una capacidad extraordinaria para sintetizar información compleja, identificar patrones abstractos y aplicar estructuras lógicas a problemas novedosos con una velocidad notable. Este nivel de inteligencia fluida sugiere que eres altamente capaz de prosperar en entornos cognitivamente exigentes como la ciencia de datos avanzada, la física teórica, la planificación estratégica compleja o la ingeniería de alto riesgo. Para maximizar este potencial, es esencial que te desafíes continuamente con problemas que te obliguen a salir de tu zona de confort, evitando el estancamiento intelectual."
  },
  Advanced: {
    en: "Your results show an Advanced level of cognitive aptitude, reflecting strong, versatile reasoning abilities across multiple domains. You possess a clear ability to grasp new and complex concepts efficiently and can apply critical thinking to solve intricate problems without becoming easily overwhelmed. This analytical edge is highly valuable in roles requiring robust decision-making, such as software development, financial analysis, or project management. While your foundational logic is strong, continued exposure to interdisciplinary challenges and advanced problem-solving exercises will further sharpen your mental agility and push you toward mastery.",
    es: "Tus resultados muestran un nivel Avanzado de aptitud cognitiva, reflejando habilidades de razonamiento fuertes y versátiles en múltiples dominios. Posees una clara capacidad para captar conceptos nuevos y complejos de manera eficiente y puedes aplicar el pensamiento crítico para resolver problemas intrincados sin abrumarte fácilmente. Esta ventaja analítica es altamente valiosa en roles que requieren una toma de decisiones robusta, como el desarrollo de software, el análisis financiero o la gestión de proyectos. Aunque tu lógica fundamental es fuerte, la exposición continua a desafíos interdisciplinarios y ejercicios avanzados de resolución de problemas afilará aún más tu agilidad mental hacia la maestría."
  },
  Solid: {
    en: "Your results reflect a Solid level of cognitive aptitude, indicating reliable and effective foundational reasoning skills. You are capable of understanding standard logical structures, following complex sequential instructions, and solving everyday analytical problems with moderate effort. You likely excel in environments that value consistency, practical problem-solving, and steady execution. To build upon this solid foundation, targeted practice in specific areas—such as spatial visualization or complex mathematical puzzles—can incrementally enhance your cognitive flexibility and speed, allowing you to tackle increasingly ambiguous challenges with greater confidence.",
    es: "Tus resultados reflejan un nivel Sólido de aptitud cognitiva, lo que indica habilidades de razonamiento fundamentales fiables y efectivas. Eres capaz de comprender estructuras lógicas estándar, seguir instrucciones secuenciales complejas y resolver problemas analíticos cotidianos con un esfuerzo moderado. Probablemente destacas en entornos que valoran la consistencia, la resolución práctica de problemas y la ejecución constante. Para construir sobre esta base sólida, la práctica dirigida en áreas específicas (como la visualización espacial o los rompecabezas matemáticos complejos) puede mejorar gradualmente tu flexibilidad y velocidad cognitiva, permitiéndote abordar desafíos cada vez más ambiguos con mayor confianza."
  },
  Developing: {
    en: "Your results suggest a Developing level of cognitive aptitude. This means that your reasoning skills are currently forming and that you may find highly abstract or deeply complex logical problems challenging at this stage. It is important to view cognitive aptitude not as a fixed trait, but as a muscle that can be strengthened through deliberate, consistent exercise. Focus on breaking down large problems into smaller, manageable steps. Engage regularly with logic puzzles, analytical reading, and fundamental mathematical concepts. Growth in this area requires patience and persistence; over time, these targeted mental workouts will significantly improve your baseline cognitive agility.",
    es: "Tus resultados sugieren un nivel en Desarrollo de aptitud cognitiva. Esto significa que tus habilidades de razonamiento se están formando y que puedes encontrar desafiantes los problemas lógicos altamente abstractos o profundamente complejos en esta etapa. Es importante ver la aptitud cognitiva no como un rasgo fijo, sino como un músculo que puede fortalecerse mediante ejercicio deliberado y constante. Concéntrate en desglosar problemas grandes en pasos más pequeños y manejables. Participa regularmente en rompecabezas lógicos, lectura analítica y conceptos matemáticos fundamentales. El crecimiento en esta área requiere paciencia y persistencia; con el tiempo, estos entrenamientos mentales específicos mejorarán significativamente tu agilidad cognitiva base."
  }
};

export const ANXIETY_LEVELS_TEXT: Record<string, { en: string; es: string }> = {
  minimal: {
    en: "Your assessment indicates a Minimal level of anxiety, suggesting a strong baseline of emotional balance. You appear to be managing daily stressors effectively, maintaining a resilient psychological state without significant disruption to your focus, sleep, or overall well-being. This is an optimal state for deep work, creativity, and nurturing personal relationships. To sustain this balance, continue practicing the healthy coping mechanisms and lifestyle habits you already have in place. Regular physical exercise, adequate sleep, and maintaining a supportive social network are excellent proactive measures to buffer against future stress.",
    es: "Tu evaluación indica un nivel Mínimo de ansiedad, sugiriendo una fuerte base de equilibrio emocional. Pareces estar manejando eficazmente los factores estresantes diarios, manteniendo un estado psicológico resiliente sin interrupciones significativas en tu enfoque, sueño o bienestar general. Este es un estado óptimo para el trabajo profundo, la creatividad y el cultivo de relaciones personales. Para sostener este equilibrio, continúa practicando los mecanismos de afrontamiento saludables y hábitos de vida que ya tienes implementados. El ejercicio físico regular, el sueño adecuado y mantener una red social de apoyo son excelentes medidas proactivas para amortiguar el estrés futuro."
  },
  mild: {
    en: "Your assessment shows a Mild level of anxiety. While generally manageable, you may be experiencing occasional tension, overthinking, or subtle disruptions to your peace of mind. This often occurs during periods of increased workload, life transitions, or minor personal conflicts. Recognizing these early signs is a powerful step in self-care. Incorporating structured relaxation techniques—such as mindfulness meditation, deep breathing exercises, or simply setting clear boundaries between work and rest—can prevent these mild symptoms from escalating. Consider establishing a dedicated 'worry time' to process concerns, allowing the rest of your day to remain focused and calm.",
    es: "Tu evaluación muestra un nivel Leve de ansiedad. Aunque generalmente manejable, puedes estar experimentando tensión ocasional, sobrepensamiento o sutiles interrupciones en tu paz mental. Esto ocurre a menudo durante períodos de mayor carga de trabajo, transiciones de vida o conflictos personales menores. Reconocer estos signos tempranos es un paso poderoso en el autocuidado. Incorporar técnicas estructuradas de relajación (como meditación mindfulness, ejercicios de respiración profunda o establecer límites claros entre trabajo y descanso) puede evitar que estos síntomas leves escalen. Considera establecer un 'tiempo de preocupación' dedicado para procesar inquietudes, permitiendo que el resto de tu día permanezca enfocado y en calma."
  },
  moderate: {
    en: "Your assessment indicates a Moderate level of anxiety, suggesting that emotional tension is beginning to have a noticeable impact on your daily life. You might be experiencing frequent worry, physical tension, difficulty concentrating, or disrupted sleep patterns. This level of stress requires intentional and proactive management. Prioritizing strict sleep hygiene, reducing caffeine intake, and engaging in regular cardiovascular exercise can help regulate your nervous system. It is highly recommended to openly discuss your feelings with a trusted friend, mentor, or wellness coach. If these feelings persist, you can seek guidance from a professional, which can provide you with tailored strategies to restore your equilibrium.",
    es: "Tu evaluación indica un nivel Moderado de ansiedad, sugiriendo que la tensión emocional está comenzando a tener un impacto notable en tu vida diaria. Podrías estar experimentando preocupación frecuente, tensión física, dificultad para concentrarte o patrones de sueño alterados. Este nivel de estrés requiere un manejo intencional y proactivo. Priorizar una estricta higiene del sueño, reducir la ingesta de cafeína y realizar ejercicio cardiovascular regular puede ayudar a regular tu sistema nervioso. Es muy recomendable hablar abiertamente sobre tus sentimientos con un amigo de confianza, mentor o coach de bienestar. Si estos sentimientos persisten, puedes buscar orientación de un profesional, lo cual puede proporcionarte estrategias adaptadas para restaurar tu equilibrio."
  },
  severe: {
    en: "Your assessment reveals a Severe level of anxiety, indicating a high degree of emotional distress that is likely interfering significantly with your daily functioning, focus, and overall quality of life. Symptoms at this level can feel overwhelming and exhausting, often manifesting as persistent dread, severe restlessness, or intense physical fatigue. It is crucial to understand that you do not have to manage this alone. Please treat this result as a strong signal to prioritize your mental health immediately. Reaching out to a qualified mental health professional, counselor, or therapist is an important and courageous step towards recovery. In the meantime, focus on absolute basic self-care: stay hydrated, eat regularly, and rest.",
    es: "Tu evaluación revela un nivel Severo de ansiedad, lo que indica un alto grado de malestar emocional que probablemente está interfiriendo de manera significativa con tu funcionamiento diario, concentración y calidad de vida en general. Los síntomas en este nivel pueden sentirse abrumadores y agotadores, manifestándose a menudo como pavor persistente, inquietud severa o fatiga física intensa. Es crucial entender que no tienes que manejar esto solo/a. Por favor, toma este resultado como una señal fuerte para priorizar tu salud mental de inmediato. Acudir a un profesional de la salud mental cualificado o terapeuta es un paso importante y valiente hacia la recuperación. Mientras tanto, concéntrate en el autocuidado básico absoluto: mantente hidratado/a, come regularmente y descansa."
  }
};

export const MOOD_LEVELS_TEXT: Record<string, { en: string; es: string }> = {
  Flourishing: {
    en: "Your results indicate a Flourishing state of emotional well-being. You are currently experiencing high levels of positivity, strong engagement with your daily activities, and a robust sense of personal meaning. This psychological state is characterized by resilience, creativity, and the energy to invest deeply in your relationships and goals. To sustain this momentum, actively practice gratitude and document the specific habits—be it your diet, social interactions, or creative outlets—that are contributing to this peak state. Understanding what drives your flourishing will serve as a vital blueprint for resilience when you inevitably face future challenges.",
    es: "Tus resultados indican un estado Floreciente de bienestar emocional. Actualmente estás experimentando altos niveles de positividad, un fuerte compromiso con tus actividades diarias y un robusto sentido de significado personal. Este estado psicológico se caracteriza por la resiliencia, la creatividad y la energía para invertir profundamente en tus relaciones y objetivos. Para sostener este impulso, practica activamente la gratitud y documenta los hábitos específicos (ya sea tu dieta, interacciones sociales o salidas creativas) que contribuyen a este estado óptimo. Comprender qué impulsa tu florecimiento servirá como un plano vital de resiliencia cuando inevitablemente enfrentes futuros desafíos."
  },
  Balanced: {
    en: "Your results suggest a Balanced emotional state. You are generally managing life's demands well, maintaining a stable mood with normal, expected fluctuations. While you function capably in most areas of your life, there may be slight room for enhancement in your overall vitality or sense of purpose. Consider this a healthy baseline. To elevate your well-being further, look for small opportunities to introduce novelty into your routine, deepen your social connections, or dedicate more time to a passion project. Small, consistent investments in your physical and mental health can naturally lift your baseline toward a flourishing state.",
    es: "Tus resultados sugieren un estado emocional Equilibrado. En general, estás manejando bien las exigencias de la vida, manteniendo un estado de ánimo estable con fluctuaciones normales y esperadas. Aunque funcionas de manera competente en la mayoría de las áreas de tu vida, puede haber un ligero margen de mejora en tu vitalidad general o sentido de propósito. Considera esto como una línea base saludable. Para elevar aún más tu bienestar, busca pequeñas oportunidades para introducir novedad en tu rutina, profundizar tus conexiones sociales o dedicar más tiempo a un proyecto que te apasione. Las pequeñas y consistentes inversiones en tu salud física y mental pueden elevar naturalmente tu línea base hacia un estado floreciente."
  },
  Struggling: {
    en: "Your assessment points to a Struggling emotional state, indicating that you are currently navigating noticeable emotional friction. You might be experiencing periods of low motivation, persistent fatigue, or a decreased interest in activities you usually enjoy. This is a common human experience, often triggered by burnout, prolonged stress, or unresolved personal issues. It is important to treat yourself with profound self-compassion during this time. Focus on 'micro-wins'—small, achievable daily goals like taking a brief walk, ensuring adequate hydration, or reaching out to a single supportive friend. Lowering your expectations of yourself temporarily while focusing on foundational self-care can create the space needed for your energy to replenish.",
    es: "Tu evaluación apunta a un estado emocional Con Dificultades, indicando que actualmente estás navegando por una fricción emocional notable. Podrías estar experimentando períodos de baja motivación, fatiga persistente o una disminución del interés en actividades que usualmente disfrutas. Esta es una experiencia humana común, a menudo desencadenada por el agotamiento, estrés prolongado o problemas personales no resueltos. Es importante tratarte con profunda autocompasión durante este tiempo. Concéntrate en 'micro-logros': pequeñas metas diarias alcanzables como dar un breve paseo, asegurar una hidratación adecuada o contactar a un solo amigo de apoyo. Bajar temporalmente las expectativas sobre ti mismo/a mientras te enfocas en el autocuidado fundamental puede crear el espacio necesario para que tu energía se reponga."
  },
  NeedsAttention: {
    en: "Your results indicate a state that Needs Attention, suggesting significant emotional distress and a heavily depleted psychological reserve. You may be dealing with profound feelings of sadness, isolation, or a pervasive sense of hopelessness that impacts your ability to function normally. Please recognize that this is a critical signal from your mind and body asking for support. Professional guidance from a therapist, counselor, or healthcare provider is strongly recommended to help you navigate this difficult period safely. Remember that you do not have to carry this burden alone; reaching out for help is the most constructive and courageous action you can take. Prioritize immediate, gentle self-care, and seeking out or speaking with your support network is always recommended.",
    es: "Tus resultados indican un estado que Necesita Atención, sugiriendo un malestar emocional significativo y una reserva psicológica fuertemente agotada. Puedes estar lidiando con profundos sentimientos de tristeza, aislamiento o una sensación generalizada de desesperanza que impacta tu capacidad para funcionar normalmente. Por favor, reconoce que esta es una señal crítica de tu mente y cuerpo pidiendo apoyo. Se recomienda encarecidamente buscar la orientación profesional de un terapeuta, consejero o proveedor de atención médica para ayudarte a navegar este difícil período de manera segura. Recuerda que no tienes que llevar esta carga solo/a; buscar ayuda es la acción más constructiva y valiente que puedes tomar. Prioriza el autocuidado inmediato y gentil; buscar o hablar con tu red de apoyo siempre es recomendable."
  }
};

export { MBTI_EXT } from './mbtiData';

export const HOLLAND_EXT: Record<string, { en: string; es: string }> = {
  R: {
    en: "As a 'Realistic' personality, you are fundamentally grounded, practical, and highly independent. You possess a strong natural inclination towards physical, mechanical, and hands-on activities. Rather than getting lost in abstract theories, you prefer clear, concrete problems with tangible solutions. You are likely very skilled with tools, machinery, or working closely with nature. In a professional setting, you thrive when given the autonomy to fix things, build structures, or operate equipment. You value tradition, common sense, and hard work. Your ideal career paths lie in fields where your physical coordination and practical problem-solving skills are put to direct use, such as engineering, agriculture, applied technology, mechanics, or the skilled trades. To maximize your potential, seek environments that reward tangible results and minimize excessive bureaucracy.",
    es: "Como personalidad 'Realista', eres fundamentalmente pragmático, enfocado y altamente independiente. Posees una fuerte inclinación natural hacia actividades físicas, mecánicas y manuales. En lugar de perderte en teorías abstractas, prefieres problemas claros y concretos con soluciones tangibles. Probablemente eres muy hábil con herramientas, maquinaria o trabajando en contacto directo con la naturaleza. En un entorno profesional, prosperas cuando se te da la autonomía para arreglar cosas, construir estructuras u operar equipos. Valoras la tradición, el sentido común y el trabajo duro. Tu trayectoria profesional ideal se encuentra en campos donde tu coordinación física y tus habilidades prácticas de resolución de problemas se utilicen directamente, como la ingeniería, agricultura, tecnología aplicada, mecánica o los oficios técnicos. Para maximizar tu potencial, busca entornos que recompensen los resultados tangibles y minimicen la burocracia excesiva."
  },
  I: {
    en: "As an 'Investigative' personality, you are driven by a profound curiosity and a relentless desire to understand how the world works. You are analytical, intellectual, and observational by nature. You excel in environments that require complex problem-solving, deep research, and the synthesis of intricate data. Rather than leading teams or focusing on social persuasion, you prefer working independently with ideas, abstract concepts, and logical puzzles. You thrive in academic or scientific settings where intellectual rigor is highly valued. Careers in scientific research, data analysis, software engineering, medicine, and higher education are particularly well-suited to your cognitive strengths. To truly flourish, you need a career that constantly challenges your intellect and allows you to dive deep into subjects without being rushed.",
    es: "Como personalidad 'Investigadora', te impulsa una profunda curiosidad y un deseo implacable de comprender cómo funciona el mundo. Eres analítico, intelectual y observador por naturaleza. Sobresales en entornos que requieren la resolución de problemas complejos, investigación profunda y la síntesis de datos intrincados. En lugar de liderar equipos o centrarte en la persuasión social, prefieres trabajar de forma independiente con ideas, conceptos abstractos y acertijos lógicos. Prosperas en entornos académicos o científicos donde el rigor intelectual es muy valorado. Carreras en investigación científica, análisis de datos, ingeniería de software, medicina y educación superior se adaptan particularmente bien a tus fortalezas cognitivas. Para florecer verdaderamente, necesitas una carrera que desafíe constantemente tu intelecto y te permita profundizar en los temas sin prisas."
  },
  A: {
    en: "As an 'Artistic' personality, you are the quintessential creator—imaginative, expressive, and highly original. You possess a deep-seated need for self-expression and strongly prefer environments that lack rigid structure and allow for spontaneity. You see the world through a unique lens, often challenging conventions and bringing fresh aesthetic or emotional perspectives to your work. Whether your medium is visual art, writing, music, or innovative design, you thrive when your work feels deeply personal and authentic. Highly structured, routine, or purely analytical jobs can feel stifling to you. To find lasting fulfillment, seek out roles in the creative industries—such as graphic design, architecture, creative writing, or performing arts—where your intuition, emotional depth, and visionary ideas are recognized as your greatest assets.",
    es: "Como personalidad 'Artística', eres el creador por excelencia: imaginativo, expresivo y altamente original. Posees una necesidad profundamente arraigada de autoexpresión y prefieres entornos que carecen de una estructura rígida y permiten la espontaneidad. Ves el mundo a través de una lente única, a menudo desafiando las convenciones y aportando nuevas perspectivas estéticas o emocionales a tu trabajo. Ya sea que tu medio sea el arte visual, la escritura, la música o el diseño innovador, prosperas cuando tu trabajo se siente profundamente personal y auténtico. Los trabajos altamente estructurados, rutinarios o puramente analíticos pueden resultarte asfixiantes. Para encontrar una realización duradera, busca roles en las industrias creativas (como diseño gráfico, arquitectura, escritura creativa o artes escénicas) donde tu intuición, profundidad emocional e ideas visionarias sean reconocidas como tus mayores activos."
  },
  S: {
    en: "As a 'Social' personality, you are the ultimate helper and connector. You are naturally empathetic, patient, and deeply attuned to the emotional needs of others. Your core motivation is to inform, heal, educate, or elevate the people around you. Unlike those who prefer working with machines or data, you draw your energy directly from meaningful human interaction. You excel at communicating complex ideas with compassion and are often the emotional anchor in your community or workplace. Careers in teaching, counseling, nursing, social work, and human resources align perfectly with your intrinsic desire to make a positive impact on individual lives. Your greatest professional satisfaction will come from roles where you can clearly see how your direct support enables others to grow and overcome their challenges.",
    es: "Como personalidad 'Social', eres el ayudante y conector definitivo. Eres naturalmente empático, paciente y estás profundamente sintonizado con las necesidades emocionales de los demás. Tu motivación principal es informar, sanar, educar o elevar a las personas que te rodean. A diferencia de aquellos que prefieren trabajar con máquinas o datos, tú obtienes tu energía directamente de la interacción humana significativa. Sobresales comunicando ideas complejas con compasión y a menudo eres el ancla emocional en tu comunidad o lugar de trabajo. Carreras en docencia, consejería, enfermería, trabajo social y recursos humanos se alinean perfectamente con tu deseo intrínseco de generar un impacto positivo en la vida de las personas. Tu mayor satisfacción profesional provendrá de roles en los que puedas ver claramente cómo tu apoyo directo permite a otros crecer y superar sus desafíos."
  },
  E: {
    en: "As an 'Enterprising' personality, you are a natural-born leader, driven by ambition, influence, and the desire to achieve significant organizational goals. You are confident, persuasive, and energetic, thriving in competitive environments where you can take risks and direct the course of action. You excel at selling ideas, mobilizing teams, and negotiating complex deals. You prefer the big picture over getting bogged down in meticulous, repetitive details. Your ability to project confidence makes people naturally gravitate toward your vision. You are best suited for dynamic, high-stakes careers such as entrepreneurship, corporate management, law, sales, or politics. To remain motivated, you need a career path that offers clear opportunities for advancement, public recognition, and the platform to exercise your formidable leadership skills.",
    es: "Como personalidad 'Emprendedora', eres un líder nato, impulsado por la ambición, la influencia y el deseo de alcanzar importantes objetivos organizacionales. Eres seguro, persuasivo y enérgico, prosperando en entornos competitivos donde puedes asumir riesgos y dirigir el curso de acción. Sobresales vendiendo ideas, movilizando equipos y negociando acuerdos complejos. Prefieres la visión panorámica en lugar de empantanarte en detalles meticulosos y repetitivos. Tu capacidad para proyectar confianza hace que las personas graviten naturalmente hacia tu visión. Eres el candidato ideal para carreras dinámicas y de alto riesgo, como el emprendimiento, la gestión corporativa, el derecho, las ventas o la política. Para mantenerte motivado, necesitas una trayectoria profesional que ofrezca claras oportunidades de ascenso, reconocimiento público y la plataforma para ejercer tus formidables habilidades de liderazgo."
  },
  C: {
    en: "As a 'Conventional' personality, you are the backbone of any successful organization. You are highly organized, methodical, and incredibly detail-oriented. You find immense satisfaction in creating order out of chaos, following established procedures, and ensuring absolute accuracy. You thrive in structured environments where the rules are clear, the expectations are defined, and your meticulous nature can be put to work. You excel at managing data, keeping records, and analyzing financial details. You generally prefer following a systematic plan rather than engaging in unstructured, highly ambiguous creative tasks. Careers in accounting, finance, database management, administration, and logistics are natural fits for your strengths. Your precision and reliability make you an indispensable asset, and you will find the most fulfillment in roles that value exactness and procedural integrity.",
    es: "Como personalidad 'Convencional', eres la columna vertebral de cualquier organización exitosa. Eres altamente organizado, metódico e increíblemente orientado al detalle. Encuentras inmensa satisfacción en crear orden a partir del caos, seguir procedimientos establecidos y asegurar una precisión absoluta. Prosperas en entornos estructurados donde las reglas son claras, las expectativas están definidas y tu naturaleza meticulosa puede ponerse a trabajar. Sobresales en la gestión de datos, mantenimiento de registros y el análisis de detalles financieros. Generalmente prefieres seguir un plan sistemático en lugar de participar en tareas creativas altamente ambiguas y sin estructura. Carreras en contabilidad, finanzas, gestión de bases de datos, administración y logística son el ajuste natural para tus fortalezas. Tu precisión y fiabilidad te convierten en un activo indispensable, y encontrarás la mayor realización en roles que valoren la exactitud y la integridad de los procedimientos."
  }
};
